In [ ]:
import torch
print(torch.__version__)

2.10.0+cu128


In [ ]:
if(torch.cuda.is_available()):
  print("yes available")
  print(f"using GPU:{torch.cuda.get_device_name(0)}")
else:
  print("not available")

yes available
using GPU:Tesla T4


# Creating a Tensor

In [ ]:
#using empty
a=torch.empty(2,3) #2d matrix of 2,3 size it gives

In [ ]:
#check type
type(a)

torch.Tensor

In [ ]:
#using zeros
torch.zeros(2,3) #all values are zeros

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [ ]:
#using ones
torch.ones(2,3) #all values are ones

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [ ]:
#using rand
torch.rand(2,3) #random values

tensor([[0.6021, 0.3313, 0.1840],
        [0.2447, 0.1056, 0.5081]])

In [ ]:
#use of seed
torch.rand(2,3) #each time you use rand it gives random numbers but sometimes you want to use same data again so you use manual seed.

tensor([[0.7526, 0.7240, 0.1715],
        [0.1157, 0.2403, 0.2530]])

In [ ]:
#manual seed

torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [ ]:
#using tensor
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
#other ways

#arange
print("using arange->", torch.arange(0,10))

#using linspace
print("using linspace->", torch.linspace(0,10,5)) #start,stop,step

#using eye
print("using eye->", torch.eye(5)) #eye means identity matrix

#using full
print("using full->", torch.full((3,3),5)) #3X3 matrix and all items should be 5

using arange-> tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
using linspace-> tensor([ 0.0000,  2.5000,  5.0000,  7.5000, 10.0000])
using eye-> tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
using full-> tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])


# Tensors shapes

In [ ]:
x=torch.tensor([[1,2,3],[1,2,3]])

In [ ]:
x.shape #ans--> 2 rows , 3 columns i.e, [2,3]

torch.Size([2, 3])

In [ ]:
torch.empty_like(x) #copy tensor with size same of x but the values will be different

tensor([[289329,      5,      5],
        [     5,      5,      5]])

In [ ]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [ ]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [ ]:
torch.rand_like(x,dtype=torch.float32)

tensor([[0.2627, 0.0428, 0.2080],
        [0.1180, 0.1217, 0.7356]])

# Tensor Data Types

In [ ]:
#find data type
x.dtype

torch.int64

In [ ]:
#assign data type
torch.tensor([1.0,2.0,3.0],dtype=torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [ ]:
torch.tensor([1,2,3],dtype=torch.float64)

tensor([1., 2., 3.], dtype=torch.float64)

In [ ]:
x.to(torch.float32)

tensor([[1., 2., 3.],
        [1., 2., 3.]])

# Mathematical Operations

**1.Scalar operation**

In [ ]:
x=torch.rand(2,2)
x

tensor([[0.7118, 0.7876],
        [0.4183, 0.9014]])

In [ ]:
#addition
x+2

tensor([[2.7118, 2.7876],
        [2.4183, 2.9014]])

In [ ]:
#subtraction
x-2

tensor([[-1.2882, -1.2124],
        [-1.5817, -1.0986]])

In [ ]:
#multiplication
x*2

tensor([[1.4235, 1.5752],
        [0.8366, 1.8028]])

In [ ]:
#division
x/3

tensor([[0.2373, 0.2625],
        [0.1394, 0.3005]])

In [ ]:
#int division
(x*100)//3

tensor([[23., 26.],
        [13., 30.]])

In [ ]:
#mod
((x*100)//3)%2

tensor([[1., 0.],
        [1., 0.]])

In [ ]:
#power
x**2

tensor([[0.5066, 0.6203],
        [0.1750, 0.8125]])

**2.Element wise operation**

In [ ]:
a=torch.rand(2,3)
b=torch.rand(2,3)
print(a)
print(b)

tensor([[0.9969, 0.7565, 0.2239],
        [0.3023, 0.1784, 0.8238]])
tensor([[0.5557, 0.9770, 0.4440],
        [0.9478, 0.7445, 0.4892]])


In [ ]:
#add
a+b

tensor([[1.5526, 1.7335, 0.6679],
        [1.2502, 0.9229, 1.3130]])

In [ ]:
#sub
a-b

tensor([[ 0.4411, -0.2205, -0.2201],
        [-0.6455, -0.5661,  0.3346]])

In [ ]:
#multiply
a*b

tensor([[0.5540, 0.7391, 0.0994],
        [0.2866, 0.1328, 0.4030]])

In [ ]:
#division
a/b

tensor([[1.7938, 0.7743, 0.5042],
        [0.3190, 0.2397, 1.6841]])

In [ ]:
#power
a**b

tensor([[0.9983, 0.7614, 0.5145],
        [0.3218, 0.2771, 0.9096]])

In [ ]:
#mod
a%b

tensor([[0.4411, 0.7565, 0.2239],
        [0.3023, 0.1784, 0.3346]])

In [ ]:
c=torch.tensor([1,-3,-6])

In [ ]:
torch.abs(c) #absolute value it gives

tensor([1, 3, 6])

In [ ]:
#negative
torch.neg(c)

tensor([-1,  3,  6])

In [ ]:
d=torch.tensor([1.2,3.4,5.6])

In [ ]:
#round
torch.round(d)

#floor
torch.floor(d)

#ceil
torch.ceil(d)

tensor([2., 4., 6.])

**3. Reduction operation**

In [ ]:
e=torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)
e

tensor([[8., 0., 7.],
        [0., 0., 9.]])

In [ ]:
#sum
torch.sum(e)

tensor(24.)

In [ ]:
#sum along columns
torch.sum(e,dim=0)

tensor([ 8.,  0., 16.])

In [ ]:
#sum along rows
torch.sum(e,dim=1)


tensor([15.,  9.])

In [ ]:
#mean
torch.mean(e)

#mean along col
torch.mean(e,dim=0)

#mean along row
torch.mean(e,dim=1)

tensor([5., 3.])

In [ ]:
#median
torch.median(e)

tensor(0.)

In [ ]:
#product
torch.prod(e)

tensor(0.)

In [ ]:
#standard deviation
torch.std(e)

tensor(4.4272)

In [ ]:
#variance
torch.var(e)

tensor(19.6000)

In [ ]:
#argmax
torch.argmax(e)

tensor(5)

In [ ]:
#argmin
torch.argmin(e)

tensor(1)

**Matrix Operation**

In [ ]:
f=torch.randint(size=(2,3), low=0, high=10)
g=torch.randint(size=(2,3), low=0, high=10)

In [ ]:
#matrix multiplication
torch.matmul(f,g.T)

tensor([[ 89, 129],
        [ 73, 117]])

In [ ]:
vector1=torch.tensor([1,2,3])
vector2=torch.tensor([2,3,5])

In [ ]:
#dot product
torch.dot(vector1, vector2)

tensor(23)

In [ ]:
f

tensor([[5, 7, 3],
        [9, 4, 0]])

In [ ]:
#transpose
torch.transpose(f,0,1)

tensor([[5, 9],
        [7, 4],
        [3, 0]])

In [ ]:
h=torch.randint(size=(2,2), low=0, high=10, dtype=torch.float32) #for finding determinant always give square matrix else it'll give RuntimeError
h

tensor([[5., 9.],
        [8., 9.]])

In [ ]:
#determinant
torch.det(h)

tensor(-27.0000)

In [ ]:
#inverse
torch.inverse(h)

tensor([[-0.3333,  0.3333],
        [ 0.2963, -0.1852]])

**5. Comparison Operation**

In [ ]:
from os.path import isjunction
i=torch.randint(size=(2,3), low=0, high=10)
j=torch.randint(size=(2,3), low=0, high=10)
print(i)
print(j)

tensor([[7, 9, 2],
        [6, 7, 7]])
tensor([[8, 3, 6],
        [1, 5, 5]])


In [ ]:
#greater than
i>j
#less than
i<j
#equals to
i==j
#not equals to
i!=j

tensor([[True, True, True],
        [True, True, True]])

**6. Special Functions**

In [ ]:
k=torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)

In [ ]:
#log
torch.log(k)
#exp
torch.exp(k)
#squareroot
torch.sqrt(k)
#sigmoid
torch.sigmoid(k)
#softmax
torch.softmax(k,dim=0)
#relu
torch.relu(k)

tensor([[0., 4., 3.],
        [8., 8., 3.]])

**7. Inplace Operations**
*_ reprensents inplace operations*

In [ ]:
m=torch.rand(2,3)
n=torch.rand(2,3)

In [ ]:
m+n

tensor([[0.6830, 0.2624, 1.9251],
        [1.2663, 0.8025, 1.1494]])

In [ ]:
m.add_(n) #add n in m but n values ramain unchanged

tensor([[0.6830, 0.2624, 1.9251],
        [1.2663, 0.8025, 1.1494]])

In [ ]:
n

tensor([[0.3451, 0.0453, 0.9798],
        [0.5548, 0.6868, 0.4920]])

In [ ]:
m.relu_() #permanent changes in m and no new tensor forms so saves space but torch.relu(m) create new tensor

tensor([[0.6830, 0.2624, 1.9251],
        [1.2663, 0.8025, 1.1494]])

In [ ]:
m

tensor([[0.6830, 0.2624, 1.9251],
        [1.2663, 0.8025, 1.1494]])

**8. Copying Tensor**

In [ ]:
a=torch.rand(2,3)
print(a)

tensor([[0.0748, 0.9605, 0.3271],
        [0.0103, 0.9516, 0.2855]])


In [ ]:
b=a
b

tensor([[0.0748, 0.9605, 0.3271],
        [0.0103, 0.9516, 0.2855]])

In [ ]:
a[0][0]=0 #here changes in 'a' makes changes in 'b' too this is not desirable

In [ ]:
b[0][0]

tensor(0.)

In [ ]:
b

tensor([[0.0000, 0.9605, 0.3271],
        [0.0103, 0.9516, 0.2855]])

In [ ]:
id(a)

133716414601392

In [ ]:
id(b) # a and b points to same memory location

133716414601392

In [ ]:
# to escape above problem we use clone function
b=a.clone()
a

tensor([[0.0000, 0.9605, 0.3271],
        [0.0103, 0.9516, 0.2855]])

In [ ]:
b

tensor([[0.0000, 0.9605, 0.3271],
        [0.0103, 0.9516, 0.2855]])

In [ ]:
a[0][2]=10

In [ ]:
b

tensor([[0.0000, 0.9605, 0.3271],
        [0.0103, 0.9516, 0.2855]])

In [ ]:
a

tensor([[ 0.0000,  0.9605, 10.0000],
        [ 0.0103,  0.9516,  0.2855]])

**9. Tensor Operations on GPU**

In [ ]:
torch.cuda.is_available()

True

In [ ]:
device=torch.device('cuda')
device

device(type='cuda')

In [ ]:
#creating a new tensor on GPU
torch.rand((2,3),device=device)

tensor([[0.3563, 0.0303, 0.7088],
        [0.2009, 0.0224, 0.9896]], device='cuda:0')

In [ ]:
#moving an existing tensor to GPU
a=torch.rand(2,3)
a

tensor([[0.2324, 0.9141, 0.7668],
        [0.1659, 0.4393, 0.2243]])

In [ ]:
d=a.to(device)
d

tensor([[0.2324, 0.9141, 0.7668],
        [0.1659, 0.4393, 0.2243]], device='cuda:0')

In [ ]:
import time

### Measuring Computation Time (CPU vs. GPU)

In [ ]:
print('--- CPU Computation ---')

# Create two random tensors on CPU
cpu_tensor1 = torch.rand(10000, 10000)
cpu_tensor2 = torch.rand(10000, 10000)

start_time_cpu = time.time()
# Perform matrix multiplication on CPU
cpu_result = torch.matmul(cpu_tensor1, cpu_tensor2)
end_time_cpu = time.time()

print(f"CPU computation time: {end_time_cpu - start_time_cpu:.4f} seconds")

--- CPU Computation ---
CPU computation time: 17.8338 seconds


In [ ]:
if torch.cuda.is_available():
    print('\n--- GPU Computation ---')
    # Create two random tensors on GPU
    gpu_tensor1 = torch.rand(10000, 10000, device=device)
    gpu_tensor2 = torch.rand(10000, 10000, device=device)

    start_time_gpu = time.time()
    # Perform matrix multiplication on GPU
    gpu_result = torch.matmul(gpu_tensor1, gpu_tensor2)
    torch.cuda.synchronize() # Wait for GPU to finish
    end_time_gpu = time.time()

    print(f"GPU computation time: {end_time_gpu - start_time_gpu:.4f} seconds")
else:
    print('\nGPU is not available, skipping GPU computation.')


--- GPU Computation ---
GPU computation time: 0.5539 seconds


**10. Reshaping Tensor**

In [ ]:
a=torch.ones(4,4)

In [ ]:
#reshape
a.reshape(2,2,2,2)

tensor([[[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]]])

In [ ]:
#flatten--> gives 1D tensor
a.flatten()

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
b=torch.rand(2,3,4)
b

tensor([[[0.2766, 0.1096, 0.8435, 0.1900],
         [0.6106, 0.1692, 0.1573, 0.1279],
         [0.6870, 0.5744, 0.2284, 0.4840]],

        [[0.3882, 0.9154, 0.9836, 0.2671],
         [0.1858, 0.1114, 0.1195, 0.6498],
         [0.7399, 0.0973, 0.7827, 0.2311]]])

In [ ]:
#permute---> used to reorder the dimensions (axes) of a tensor without changing its data.
b.permute(2,1,0)

tensor([[[0.9542, 0.4459],
         [0.1936, 0.1039],
         [0.1365, 0.2342]],

        [[0.3189, 0.9211],
         [0.6421, 0.3961],
         [0.3375, 0.3785]],

        [[0.4178, 0.7100],
         [0.9991, 0.0262],
         [0.6435, 0.2034]],

        [[0.2353, 0.3965],
         [0.7837, 0.9210],
         [0.1402, 0.8454]]])

In [ ]:
#unsqueeze --> konse position pe naya dim add krna chahte ho
c=torch.rand(226,226,3) #--> typical image size
c.unsqueeze(2).shape

torch.Size([226, 226, 1, 3])

In [ ]:
#squeeze
d=torch.rand(1,20)
d.squeeze(0).shape

torch.Size([20])